# Generated by Django 5.1 on 2024-08-25 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_about_companyinfo_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacts',
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='contact/'),
        ),
    ]
