# Generated by Django 5.1 on 2024-09-04 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_excursion_price_exhibition_price_ticket_excursion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket_excursion',
            name='discount_code',
        ),
        migrations.RemoveField(
            model_name='ticket_exhibition',
            name='discount_code',
        ),
    ]
