# Generated by Django 5.1 on 2024-09-04 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_ticket_excursion_discount_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_excursion',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket_exhibition',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
