# Generated by Django 5.1 on 2024-09-04 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_ticket_excursion_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_excursion',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.promocode'),
        ),
        migrations.AddField(
            model_name='ticket_exhibition',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.promocode'),
        ),
    ]
