# Generated by Django 5.1 on 2024-09-12 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_ticket_excursion_promo_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/'),
        ),
    ]
